services:
  - type: web
    name: predictabot-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:all
    envVars:
      - key: NODE_VERSION
        value: 20
    plan: free
